# Generated by Django 5.1.1 on 2024-12-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreactchiko', '0020_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
