# Generated by Django 5.1.4 on 2026-01-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactchiko', '0023_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
