# Generated by Django 5.1.4 on 2026-03-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreactchiko', '0025_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
