# Generated by Django 5.1.4 on 2026-04-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactchiko', '0027_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
