# Generated by Django 5.1.4 on 2026-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactchiko', '0029_review_user_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='dishes/default.jpg', upload_to='dishes/'),
        ),
    ]
