# Generated by Django 5.1.4 on 2026-04-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactchiko', '0030_alter_dish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(upload_to='dishes/'),
        ),
    ]
