# Generated by Django 5.1.4 on 2026-06-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='massage',
            new_name='message',
        ),
    ]
